version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - save_cache:
          key: v1-dependencies-{{ checksum "./package-lock.json" }}
          paths:
            - node_modules
      - store_artifacts:
          path: ./build
          destination: build
